### ISSUE TITLE
Applications should have following accessories:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#172]
- [x] Control and Actuation: Should have Buoyancy Control System, acoustic timer actuator, Actuation valve, MN-8

- [x] Marine Construction: Should have SP, PFE, EFB, Pipe Plugger (Remove BCS and add Pipe Plugger)

- [x] Public Safety: Should have ACLB, VRS, EFB, RRS, BRS ( Add Aircraft Liftbag, and enclosed float bags

- [x] Shipyard Draft Reduction should have SP, EFB, PB WLTB (Remove Lifeboat Davit, add Enclosed Flotation Bags)

- [x] Ordnance Disposal should have MK II, surface actuation, BCS-ATA  (Remove RRS, add ??? surface actuation ???)

- [x] Research should have Commercial lift bags, EFB, PFE (Remove BCS, RRS, add Professional Enclosed Flotation) 

Source: https://docs.google.com/spreadsheets/d/0B6ZQMsMmAFJLYUEyZUF6bm5kSVBEdXFzX2lvLXVlMHdyNjFF/edit#gid=400336307

**Comment by aguillen1** [comment]
@jtuckertw These pages do not have an accessory component. They do have a "Product Association" and "Associated Case Study" component. Please let me know how you'd like me to proceed.

**Comment by jtuckertw** [comment]
@aguillen1 oh crap - you are so totally right.  This is out of scope due to the way the design was approved.  Thank you!  Keeping open - assigning to me.

**Comment by jtuckertw** [comment]
@aguillen1 on further evaluation not all of the products requested are accessories - I marked the items that can be done, and those that contain accessories are back in my court.  Would you be able to work on this one again, please?

**Comment by aguillen1** [comment]
@jtuckertw 

- Control and Actuation: actuation valve, acoustic timer actuator and MN-8 do not exist on the current website as accessories. Buoyancy Control has been added, Mark V and Custom Solutions have been removed. Please let me know if they need to be added again: http://subsalve.wpengine.com/control-and-actuation

-Marine Construction: Ready for QA: http://subsalve.wpengine.com/marine-construction

- Ordnance Disposal: MK II does not exist,  surface actuation does not exist - added "control and actuation" instead. Please let me know if you'd like me to remove, otherwise ready for QA: http://subsalve.wpengine.com/ordinance-disposal

- Research: Ready for QA http://subsalve.wpengine.com/research

**Comment by aguillen1** [comment]
@jtuckertw 
Public safety also ready for QA: http://subsalve.wpengine.com/public-safety
Shipyard Draft reduction for QA: http://subsalve.wpengine.com/shipyard-draft-reduction

**Comment by jtuckertw** [comment]
@aguillen1  Looks great - one small change:
Aircraft Lift Bag card needs to be plural "Bags" on http://subsalve.wpengine.com/public-safety

**Comment by aguillen1** [comment]
@jtuckertw Made that change!

**Comment by jtuckertw** [comment]
Hmm not showing @cmoosman1 @aguillen1   Is this a backend thing that hasn't shown up on the front yet?

**Comment by aguillen1** [comment]
@jtuckertw It should be on there now: http://subsalve.wpengine.com/public-safety
