### ISSUE TITLE
Rich hates the hamburger menu showing on his laptop

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#220]
One last option -  Get rid of the downward pointing arrow on three of the menu options 
decrease the breakpoint as low as it will go so that it does not break to mobile view on a laptop - 
I'm open for other solutions.

**Comment by jthiel16** [comment]
I'd rather not remove the arrows, I think it won't save us much space anyway. If we were to remove anything at a certain breakpoint—before going to hamburger menu— I'd say maybe the Download button? Since that CTA/link is a couple other places on the page

But, I'd be curious to know what screen resolution he's viewing on, and if he's perhaps zoomed in higher than 100%? Is anyone else having the same issue?

**Comment by jtuckertw** [comment]
@jthiel16 - Yes I have the same issue on my laptop 1366x768 screen dimension
Can we compress the download button, somehow?  They will have a fit if we take it off the menu at this point.

**Comment by jthiel16** [comment]
@jtuckertw Yeah I could see playing with that download button to tighten it up a bit. We could remove "download" as long as we add an icon, like this to save some space:
![IMG_1045](https://user-images.githubusercontent.com/35710312/77784251-77853a00-7017-11ea-8abb-cb97190ce89e.jpg)
I'm not sure how much space we need to save though. Another option would be reducing the size of the entire nav (text size and logo size), but I'm not sure how much effort that is for Criss
