### ISSUE TITLE
Pill Button Hover states:

### ISSUE THREAD

**Issue by jtuckertw** [Tallwave/PIC-Subsalve#47]
I'd like to add/adjust hover states for any instances of the pill buttons. Right now some of them don't do anything, and some of them hover to white text on yellow, which is hard to read.

I added a file to Zeplin with what I'm thinking: zpl.io/2E1Ge6y

Here's a screengrab too:
https://drive.google.com/file/d/174AWbPl8DMZ-u9slpypKaJ6RIXhBgd1D/view?usp=sharing

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Please validate and close if all is good - thanks!

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw It looks like some of the buttons got updated but there are a handful of spots that still need it:

1. The "Contact Us" button in the global form component
<img width="614" alt="Screen Shot 2019-11-15 at 10 27 15 AM" src="https://user-images.githubusercontent.com/35710312/68965548-4a876780-0799-11ea-9ebf-cc0d9651326b.png">

2. The Case Study cards (throughout the site and on the Case Studies page)
<img width="777" alt="Screen Shot 2019-11-15 at 10 27 01 AM" src="https://user-images.githubusercontent.com/35710312/68965591-60952800-0799-11ea-8ced-bb680d2beef9.png">

3. On the Case Studies page, the featured CS card
<img width="1221" alt="Screen Shot 2019-11-15 at 10 34 13 AM" src="https://user-images.githubusercontent.com/35710312/68965667-9803d480-0799-11ea-9dac-f26d858a5443.png">

4. On the News page, in each of the cards
<img width="690" alt="Screen Shot 2019-11-15 at 10 27 48 AM" src="https://user-images.githubusercontent.com/35710312/68965723-bff33800-0799-11ea-923d-fd759e0321d4.png">

5. On the Contact page, the "Get Directions" button
<img width="654" alt="Screen Shot 2019-11-15 at 10 34 34 AM" src="https://user-images.githubusercontent.com/35710312/68965931-32fcae80-079a-11ea-9d3e-ab0219af59f7.png">

**Comment by cmoosman1** [comment]
@jtuckertw - This is resolved in the current build

**Comment by jtuckertw** [comment]
@jthiel16 Jason, Can you re-review this, please.  It looks like some have been corrected but others have not.,  Thanks!

**Comment by jthiel16** [comment]
@cmoosman1 @jtuckertw 

1. On the Contact Us page, change the "Get Directions" text to white AND all caps, and make the entire button area clickable
<img width="348" alt="Screen Shot 2019-12-03 at 9 47 28 AM" src="https://user-images.githubusercontent.com/35710312/70071347-7a64a680-15b2-11ea-9497-2f98a236113f.png">

2. On the News page, when hovering over news card, change the text and external link icon both to black (instead of white)
<img width="602" alt="Screen Shot 2019-12-03 at 9 51 53 AM" src="https://user-images.githubusercontent.com/35710312/70071469-a97b1800-15b2-11ea-89f8-8d461e4d4c24.png">

**Comment by jtuckertw** [comment]
Get Directions button text should be white on Contact Page

**Comment by jtuckertw** [comment]
Fixed!
